
AllCops:
  # The Excludes section was necessitated by `guard-rubocop`, which invokes
  # RuboCop in a way sufficiently different than `bundle exec rubocop` that all
  # these exclusions aren't implicitly ignored. Oh, well.
  Exclude:
  - '*file'
  - '*.gemspec'
  - 'bin/**/*'
  - 'scripts/**/*'
  - 'test/**/*'
  - 'tmp/**/*'
  TargetRubyVersion: 2.5

Metrics/BlockLength:
  Max: 300
  Include:
    - 'test/**/*_test.rb'

Metrics/ModuleLength:
  Max: 300
  Include:
    - 'test/**/*_test.rb'

Style/CommentedKeyword:
  Enabled: false

Style/Documentation:
  Enabled: false
